### ISSUE TITLE
Error with async arrow functions: "Parsing error: Unexpected token =>"

### ISSUE THREAD

**Issue by niallcro** [sumitgoelpw/eslint-config-sumitgoelpw#1]
@sumitgoelpw could you please update the below to solve this issue: https://github.com/eslint/eslint/issues/8126

```
  'parserOptions': {
    'ecmaVersion': 8,
    'sourceType': 'module'
  },
```

**Comment by StarryShark** [comment]
@niallcro Please feel free to send a pull request.

**Comment by niallcro** [comment]
@sumitgoelpw pull request sent

**Comment by StarryShark** [comment]
Merged. Thank you!
